version: "3.9"
services:
  postgresdb:
    build: ./postgres
    image: ilyakozak/nodejs-rs-school_postgresdb
    restart: always
    networks: 
      - rest-api-net
    environment: 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
  nodejsapp:
    build: .
    image: ilyakozak/nodejs-rs-school_nodejsapp
    depends_on: 
      - postgresdb
    restart: always
    networks: 
      - rest-api-net
    ports: 
      - ${PORT}:${PORT}
    volumes:
      - ./src:/app/src

networks: 
  rest-api-net:
    driver: bridge

volumes:
  postgres-data: